version: '3.1'

services:
  db:
    build:
      dockerfile: dockerfile
      context: ./
    environment:
      POSTGRES_USER: Larisa
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ~/db_fit/data:/var/lib/postgresql/data
